import { createStyleSheet } from 'react-native-unistyles';

export const customSectionListStyles = createStyleSheet(theme => ({
  addSectionBtn: {
    alignItems: 'center',
    backgroundColor: theme.color.primary,
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 24,
    marginTop: 8,
    paddingVertical: 12,
  },
  addSectionBtnText: {
    color: theme.color.onPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  card: {
    backgroundColor: theme.color.background,
    borderRadius: 18,
    elevation: 2,
    marginBottom: 18,
    padding: 16,
    shadowColor: theme.color.shadow,
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  cardHeader: {
    color: theme.color.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  cardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  errorText: {
    color: theme.color.error,
    fontSize: 13,
    marginBottom: 4,
    marginTop: 8,
  },
  input: {
    backgroundColor: theme.color.inputBackground,
    borderColor: theme.color.inputBorder,
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 15,
    padding: 12,
  },
  modalCancelBtn: {
    backgroundColor: theme.color.surface,
    borderRadius: 16,
    paddingHorizontal: 32,
    paddingVertical: 12,
  },
  modalCancelBtnText: {
    color: theme.color.textSecondary,
    fontSize: 15,
    fontWeight: 'bold',
  },
  modalCloseBtn: {
    alignItems: 'center',
    marginTop: 12,
  },
  modalContent: {
    alignItems: 'center',
    backgroundColor: theme.color.background,
    borderRadius: 18,
    elevation: 4,
    minWidth: 260,
    padding: 28,
    shadowColor: theme.color.shadow,
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: theme.color.overlay,
    flex: 1,
    justifyContent: 'center',
  },
  modalPrimaryBtn: {
    backgroundColor: theme.color.primary,
    borderRadius: 16,
    marginBottom: 10,
    paddingHorizontal: 32,
    paddingVertical: 12,
  },
  modalPrimaryBtnText: {
    color: theme.color.onPrimary,
    fontSize: 15,
    fontWeight: 'bold',
  },
  modalTitle: {
    color: theme.color.textPrimary,
    fontSize: 17,
    fontWeight: 'bold',
    marginBottom: 18,
    textAlign: 'center',
  },
  primaryText: {
    color: theme.color.primary,
    fontSize: 13,
    fontWeight: 'bold',
  },
  removeBtn: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: theme.color.errorBackground,
    borderRadius: 12,
    flexDirection: 'row',
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  removeBtnText: {
    color: theme.color.error,
    fontSize: 13,
    fontWeight: 'bold',
  },
  sectionTitle: {
    color: theme.color.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  switchLabel: {
    color: theme.color.textSecondary,
    fontSize: 13,
    fontWeight: 'bold',
    marginHorizontal: 4,
  },
  switchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  typeBtn: {
    alignItems: 'center',
    backgroundColor: theme.color.primaryLight,
    borderRadius: 12,
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  wrapper: {
    padding: 16,
  },
}));
